---
  - name: Get ip address of current host
    debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

  - name: Scan ssh public key for each host
    shell: "ssh-keyscan {{ item }},`dig +short {{ item }}`"
    with_items: "{{ ssh_known_hosts }}"
    register: ssh_known_host_results
    ignore_errors: yes

  - name: Update/add the public key in/to known_hosts file
    known_hosts:
      name: "{{ item.item }}"
      key: "{{ item.stdout }}"
      path: "{{ ssh_known_hosts_file }}"
    with_items: "{{ ssh_known_host_results.results }}"
